require_relative 'gurps_com_cal/version'
require_relative 'gurps_com_cal/roll'
require_relative 'gurps_com_cal/character'
require_relative 'gurps_com_cal/combatant'
require_relative 'gurps_com_cal/weapon'
